// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/chunk_service.proto

package chunkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadFileRequest_Metadata
	//	*UploadFileRequest_ChunkData
	Data          isUploadFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadFileRequest) GetData() isUploadFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadFileRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadFileRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadFileRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadFileRequest_Data interface {
	isUploadFileRequest_Data()
}

type UploadFileRequest_Metadata struct {
	// First message in the stream: file metadata.
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadFileRequest_ChunkData struct {
	// Subsequent messages: raw file bytes (64KB frames).
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadFileRequest_Metadata) isUploadFileRequest_Data() {}

func (*UploadFileRequest_ChunkData) isUploadFileRequest_Data() {}

type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMetadata) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadMetadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type UploadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileChecksum  string                 `protobuf:"bytes,1,opt,name=file_checksum,json=fileChecksum,proto3" json:"file_checksum,omitempty"` // SHA-256 of the entire file
	TotalSize     int64                  `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`         // Total file size in bytes
	ChunkCount    int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`      // Number of chunks produced
	NewChunks     int32                  `protobuf:"varint,4,opt,name=new_chunks,json=newChunks,proto3" json:"new_chunks,omitempty"`         // Chunks that were actually new (not deduped)
	DedupChunks   int32                  `protobuf:"varint,5,opt,name=dedup_chunks,json=dedupChunks,proto3" json:"dedup_chunks,omitempty"`   // Chunks that already existed (dedup hits)
	Chunks        []*ChunkInfo           `protobuf:"bytes,6,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileResponse) Reset() {
	*x = UploadFileResponse{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileResponse) ProtoMessage() {}

func (x *UploadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileResponse.ProtoReflect.Descriptor instead.
func (*UploadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadFileResponse) GetFileChecksum() string {
	if x != nil {
		return x.FileChecksum
	}
	return ""
}

func (x *UploadFileResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *UploadFileResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *UploadFileResponse) GetNewChunks() int32 {
	if x != nil {
		return x.NewChunks
	}
	return 0
}

func (x *UploadFileResponse) GetDedupChunks() int32 {
	if x != nil {
		return x.DedupChunks
	}
	return 0
}

func (x *UploadFileResponse) GetChunks() []*ChunkInfo {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type ChunkInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`                                   // SHA-256 hex of chunk content
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                  // Chunk size in bytes
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`                                // Position in file (0-based)
	IsDuplicate   bool                   `protobuf:"varint,4,opt,name=is_duplicate,json=isDuplicate,proto3" json:"is_duplicate,omitempty"` // True if this chunk already existed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkInfo) Reset() {
	*x = ChunkInfo{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkInfo) ProtoMessage() {}

func (x *ChunkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkInfo.ProtoReflect.Descriptor instead.
func (*ChunkInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{3}
}

func (x *ChunkInfo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ChunkInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ChunkInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ChunkInfo) GetIsDuplicate() bool {
	if x != nil {
		return x.IsDuplicate
	}
	return false
}

type DownloadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHashes   []string               `protobuf:"bytes,1,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // Ordered list of chunk hashes (the manifest)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileRequest) Reset() {
	*x = DownloadFileRequest{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileRequest) ProtoMessage() {}

func (x *DownloadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileRequest.ProtoReflect.Descriptor instead.
func (*DownloadFileRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadFileRequest) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type DownloadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                // Raw chunk bytes (streamed in order)
	ChunkHash     string                 `protobuf:"bytes,2,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`     // Hash of the chunk being sent
	ChunkIndex    int32                  `protobuf:"varint,3,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"` // Index in the manifest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadFileResponse) Reset() {
	*x = DownloadFileResponse{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadFileResponse) ProtoMessage() {}

func (x *DownloadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadFileResponse.ProtoReflect.Descriptor instead.
func (*DownloadFileResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadFileResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadFileResponse) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *DownloadFileResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type DeleteChunksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkHashes   []string               `protobuf:"bytes,1,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // Chunk hashes to delete from MinIO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunksRequest) Reset() {
	*x = DeleteChunksRequest{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunksRequest) ProtoMessage() {}

func (x *DeleteChunksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunksRequest.ProtoReflect.Descriptor instead.
func (*DeleteChunksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteChunksRequest) GetChunkHashes() []string {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type DeleteChunksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // Number of chunks actually removed from storage
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // Number of chunks that failed to delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChunksResponse) Reset() {
	*x = DeleteChunksResponse{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChunksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChunksResponse) ProtoMessage() {}

func (x *DeleteChunksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChunksResponse.ProtoReflect.Descriptor instead.
func (*DeleteChunksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChunksResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *DeleteChunksResponse) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy" or "unhealthy"
	MinioConnected bool                   `protobuf:"varint,2,opt,name=minio_connected,json=minioConnected,proto3" json:"minio_connected,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_chunk_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chunk_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chunk_service_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMinioConnected() bool {
	if x != nil {
		return x.MinioConnected
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_proto_chunk_service_proto protoreflect.FileDescriptor

const file_api_proto_chunk_service_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/chunk_service.proto\x12\rdfms.chunk.v1\"y\n" +
	"\x11UploadFileRequest\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.dfms.chunk.v1.UploadMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"c\n" +
	"\x0eUploadMetadata\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"\xed\x01\n" +
	"\x12UploadFileResponse\x12#\n" +
	"\rfile_checksum\x18\x01 \x01(\tR\ffileChecksum\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"new_chunks\x18\x04 \x01(\x05R\tnewChunks\x12!\n" +
	"\fdedup_chunks\x18\x05 \x01(\x05R\vdedupChunks\x120\n" +
	"\x06chunks\x18\x06 \x03(\v2\x18.dfms.chunk.v1.ChunkInfoR\x06chunks\"l\n" +
	"\tChunkInfo\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12!\n" +
	"\fis_duplicate\x18\x04 \x01(\bR\visDuplicate\"8\n" +
	"\x13DownloadFileRequest\x12!\n" +
	"\fchunk_hashes\x18\x01 \x03(\tR\vchunkHashes\"j\n" +
	"\x14DownloadFileResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\x02 \x01(\tR\tchunkHash\x12\x1f\n" +
	"\vchunk_index\x18\x03 \x01(\x05R\n" +
	"chunkIndex\"8\n" +
	"\x13DeleteChunksRequest\x12!\n" +
	"\fchunk_hashes\x18\x01 \x03(\tR\vchunkHashes\"^\n" +
	"\x14DeleteChunksResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\"\x0f\n" +
	"\rHealthRequest\"k\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12'\n" +
	"\x0fminio_connected\x18\x02 \x01(\bR\x0eminioConnected\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xde\x02\n" +
	"\fChunkService\x12S\n" +
	"\n" +
	"UploadFile\x12 .dfms.chunk.v1.UploadFileRequest\x1a!.dfms.chunk.v1.UploadFileResponse(\x01\x12Y\n" +
	"\fDownloadFile\x12\".dfms.chunk.v1.DownloadFileRequest\x1a#.dfms.chunk.v1.DownloadFileResponse0\x01\x12W\n" +
	"\fDeleteChunks\x12\".dfms.chunk.v1.DeleteChunksRequest\x1a#.dfms.chunk.v1.DeleteChunksResponse\x12E\n" +
	"\x06Health\x12\x1c.dfms.chunk.v1.HealthRequest\x1a\x1d.dfms.chunk.v1.HealthResponseB+Z)github.com/AnirudhSinghRajora/DFMS/api/proto/chunkpbb\x06proto3"

var (
	file_api_proto_chunk_service_proto_rawDescOnce sync.Once
	file_api_proto_chunk_service_proto_rawDescData []byte
)

func file_api_proto_chunk_service_proto_rawDescGZIP() []byte {
	file_api_proto_chunk_service_proto_rawDescOnce.Do(func() {
		file_api_proto_chunk_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chunk_service_proto_rawDesc), len(file_api_proto_chunk_service_proto_rawDesc)))
	})
	return file_api_proto_chunk_service_proto_rawDescData
}

var file_api_proto_chunk_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_proto_chunk_service_proto_goTypes = []any{
	(*UploadFileRequest)(nil),    // 0: dfms.chunk.v1.UploadFileRequest
	(*UploadMetadata)(nil),       // 1: dfms.chunk.v1.UploadMetadata
	(*UploadFileResponse)(nil),   // 2: dfms.chunk.v1.UploadFileResponse
	(*ChunkInfo)(nil),            // 3: dfms.chunk.v1.ChunkInfo
	(*DownloadFileRequest)(nil),  // 4: dfms.chunk.v1.DownloadFileRequest
	(*DownloadFileResponse)(nil), // 5: dfms.chunk.v1.DownloadFileResponse
	(*DeleteChunksRequest)(nil),  // 6: dfms.chunk.v1.DeleteChunksRequest
	(*DeleteChunksResponse)(nil), // 7: dfms.chunk.v1.DeleteChunksResponse
	(*HealthRequest)(nil),        // 8: dfms.chunk.v1.HealthRequest
	(*HealthResponse)(nil),       // 9: dfms.chunk.v1.HealthResponse
}
var file_api_proto_chunk_service_proto_depIdxs = []int32{
	1, // 0: dfms.chunk.v1.UploadFileRequest.metadata:type_name -> dfms.chunk.v1.UploadMetadata
	3, // 1: dfms.chunk.v1.UploadFileResponse.chunks:type_name -> dfms.chunk.v1.ChunkInfo
	0, // 2: dfms.chunk.v1.ChunkService.UploadFile:input_type -> dfms.chunk.v1.UploadFileRequest
	4, // 3: dfms.chunk.v1.ChunkService.DownloadFile:input_type -> dfms.chunk.v1.DownloadFileRequest
	6, // 4: dfms.chunk.v1.ChunkService.DeleteChunks:input_type -> dfms.chunk.v1.DeleteChunksRequest
	8, // 5: dfms.chunk.v1.ChunkService.Health:input_type -> dfms.chunk.v1.HealthRequest
	2, // 6: dfms.chunk.v1.ChunkService.UploadFile:output_type -> dfms.chunk.v1.UploadFileResponse
	5, // 7: dfms.chunk.v1.ChunkService.DownloadFile:output_type -> dfms.chunk.v1.DownloadFileResponse
	7, // 8: dfms.chunk.v1.ChunkService.DeleteChunks:output_type -> dfms.chunk.v1.DeleteChunksResponse
	9, // 9: dfms.chunk.v1.ChunkService.Health:output_type -> dfms.chunk.v1.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_chunk_service_proto_init() }
func file_api_proto_chunk_service_proto_init() {
	if File_api_proto_chunk_service_proto != nil {
		return
	}
	file_api_proto_chunk_service_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadFileRequest_Metadata)(nil),
		(*UploadFileRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chunk_service_proto_rawDesc), len(file_api_proto_chunk_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chunk_service_proto_goTypes,
		DependencyIndexes: file_api_proto_chunk_service_proto_depIdxs,
		MessageInfos:      file_api_proto_chunk_service_proto_msgTypes,
	}.Build()
	File_api_proto_chunk_service_proto = out.File
	file_api_proto_chunk_service_proto_goTypes = nil
	file_api_proto_chunk_service_proto_depIdxs = nil
}
